// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFtec2-HKQ4f7FxrxiJK5tQi1-n-dygXA',
    appId: '1:1024989914520:web:8a9918394c48e2e259b7ed',
    messagingSenderId: '1024989914520',
    projectId: 'my-project-bb949',
    authDomain: 'my-project-bb949.firebaseapp.com',
    storageBucket: 'my-project-bb949.firebasestorage.app',
    measurementId: 'G-P0X53TGJ3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-fSY0108KIg8_AIB2w3mbg4G8zJLYyyE',
    appId: '1:1024989914520:android:eba16a546526a7c059b7ed',
    messagingSenderId: '1024989914520',
    projectId: 'my-project-bb949',
    storageBucket: 'my-project-bb949.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwC9L2b0_tu7o2lbwkbSLQ8svBxWHO7WI',
    appId: '1:1024989914520:ios:4f63d9b446c56fc159b7ed',
    messagingSenderId: '1024989914520',
    projectId: 'my-project-bb949',
    storageBucket: 'my-project-bb949.firebasestorage.app',
    iosBundleId: 'com.minje.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwC9L2b0_tu7o2lbwkbSLQ8svBxWHO7WI',
    appId: '1:1024989914520:ios:cdee0681b8e3707759b7ed',
    messagingSenderId: '1024989914520',
    projectId: 'my-project-bb949',
    storageBucket: 'my-project-bb949.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFtec2-HKQ4f7FxrxiJK5tQi1-n-dygXA',
    appId: '1:1024989914520:web:4346a66b3becafaf59b7ed',
    messagingSenderId: '1024989914520',
    projectId: 'my-project-bb949',
    authDomain: 'my-project-bb949.firebaseapp.com',
    storageBucket: 'my-project-bb949.firebasestorage.app',
    measurementId: 'G-9110KB3C97',
  );

}